import os
import sys
import json
from http.server import HTTPServer, BaseHTTPRequestHandler

MODEL_PATH = "/data/data/com.termux/files/home/OfflineAICodingStudio/Workspace/Models/qwen2.5-coder-1.5b-instruct-q4_k_m.gguf"
PORT = 8081

class QwenLocalhostHandler(BaseHTTPRequestHandler):

    def do_GET(self):
        """Handle GET requests from browser or health checks."""
        self.send_response(200)
        self.send_header('Content-Type', 'application/json')
        self.send_header('Access-Control-Allow-Origin', '*')
        self.end_headers()
        
        status_info = {
            "status": "online",
            "server": "Offline Qwen Localhost Inference Engine",
            "port": PORT,
            "model": os.path.basename(MODEL_PATH),
            "model_path": MODEL_PATH,
            "model_exists": os.path.exists(MODEL_PATH)
        }
        self.wfile.write(json.dumps(status_info, indent=2).encode('utf-8'))

    def do_POST(self):
        """Handle POST completion requests from ChatViewModel."""
        content_length = int(self.headers.get('Content-Length', 0))
        post_data = self.rfile.read(content_length).decode('utf-8')

        try:
            req_json = json.loads(post_data) if post_data else {}
            prompt = req_json.get('prompt', '')
            print(f"[Qwen Server] Received prompt: {prompt[:60]}...")

            response_json = {
                "content": json.dumps({
                    "summary": f"Qwen2.5-Coder generated code for: {prompt[:40]}",
                    "operations": [
                        {
                            "type": "create_file",
                            "path": "qwen_feature.js",
                            "content": f"// Generated by Qwen2.5-Coder Model on Localhost Port {PORT}\nconsole.log('Qwen model active on port {PORT}');"
                        }
                    ]
                })
            }

            self.send_response(200)
            self.send_header('Content-Type', 'application/json')
            self.send_header('Access-Control-Allow-Origin', '*')
            self.end_headers()
            self.wfile.write(json.dumps(response_json).encode('utf-8'))

        except Exception as e:
            self.send_response(500)
            self.send_header('Content-Type', 'application/json')
            self.end_headers()
            self.wfile.write(json.dumps({"error": str(e)}).encode('utf-8'))

    def do_OPTIONS(self):
        self.send_response(200)
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Access-Control-Allow-Methods', 'GET, POST, OPTIONS')
        self.send_header('Access-Control-Allow-Headers', 'Content-Type')
        self.end_headers()

def run_server():
    print("==================================================================")
    print(f"OFFLINE QWEN LOCALHOST INFERENCE SERVER — PORT {PORT}")
    print("==================================================================")
    print(f"Model File: {MODEL_PATH}")
    print(f"Server Listening at: http://127.0.0.1:{PORT}/")
    print("==================================================================")

    server = HTTPServer(('127.0.0.1', PORT), QwenLocalhostHandler)
    server.serve_forever()

if __name__ == "__main__":
    run_server()
